from jarvis_leaderboard.rebuild import get_results,get_metric_value
names,vals=get_results(bench_name='AI-MLFF-forces-mlearn_Ni-test-multimae.csv.zip')
res=get_metric_value(csv_path='/wrk/knc6/Software/alignn_calc/jarvis_leaderboard/jarvis_leaderboard/contributions/alignnff_wt1_mlearn_only_megnet/AI-MLFF-forces-mlearn_Ni-test-multimae.csv.zip',plot_filename='Ni_forces.png')
print ('Ni',names)
print(vals)
res=get_metric_value(csv_path='/wrk/knc6/Software/alignn_calc/jarvis_leaderboard/jarvis_leaderboard/contributions/alignnff_wt1_mlearn_only_megnet/AI-MLFF-forces-mlearn_Cu-test-multimae.csv.zip',plot_filename='Cu_forces.png')
names,vals=get_results(bench_name='AI-MLFF-forces-mlearn_Cu-test-multimae.csv.zip')
print ('Cu',names)
print(vals)
res=get_metric_value(csv_path='/wrk/knc6/Software/alignn_calc/jarvis_leaderboard/jarvis_leaderboard/contributions/alignnff_wt1_mlearn_only_megnet/AI-MLFF-forces-mlearn_Si-test-multimae.csv.zip',plot_filename='Si_forces.png')
names,vals=get_results(bench_name='AI-MLFF-forces-mlearn_Si-test-multimae.csv.zip')
print ('Si',names)
print(vals)
res=get_metric_value(csv_path='/wrk/knc6/Software/alignn_calc/jarvis_leaderboard/jarvis_leaderboard/contributions/alignnff_wt1_mlearn_only_megnet/AI-MLFF-forces-mlearn_Mo-test-multimae.csv.zip',plot_filename='Mo_forces.png')
names,vals=get_results(bench_name='AI-MLFF-forces-mlearn_Mo-test-multimae.csv.zip')
print ('Mo',names)
print(vals)
